# Configuration globale de Nginx
events { worker_connections 1024; }

http {
    # Définition de notre serveur virtuel
    server {
        listen 80; # Nginx écoute sur le port standard HTTP (80)
        server_name localhost;
        # 1. ROUTAGE VERS LE FRONTEND (La Racine)
        location / {
            proxy_pass http://frontend:80; # Ou le port interne de votre conteneur Frontend (ex: 5173 pour Vite)
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        # -------------------------------------------------------------
        # Rule 1 : Si l'adresse commence par /auth, on envoie vers auth-service
        # -------------------------------------------------------------
        location /auth/ {
            # "auth-service" sera le nom du conteneur Docker (défini au Sprint 6)
            proxy_pass http://auth-service:8001; 
            
            # Lignes de sécurité standards pour transmettre les vraies infos du client
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # -------------------------------------------------------------
        # Rule 2 : Si l'adresse commence par /metrics, on envoie vers metrics-service
        # -------------------------------------------------------------
        location /metrics/ {
            proxy_pass http://metrics-service:8002;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # -------------------------------------------------------------
        # Rule 3 : Si l'adresse commence par /alerts, on envoie vers alerts-service
        # -------------------------------------------------------------
        location /alerts/ {
            proxy_pass http://alerts-service:8003;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}